apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gateway.yaml
  - service-template.yaml
  - servicemonitor.yaml
  - postgres.yaml
  - match-service.yaml
  - payment-service.yaml
