apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gateway.yaml
  - service-template.yaml
  - servicemonitor.yaml
  - postgres.yaml
  - match-service.yaml
  - payment-service.yaml
  - venue-service.yaml
  - identity-service.yaml
  - kafka.yaml
  - kafka-topics-job.yaml
configMapGenerator:
  - name: postgres-init
    files:
      - init-databases.sh
  - name: kafka-topics
    files:
      - create-topics.sh
