apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-template
  labels:
    app: service-template
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-template
  template:
    metadata:
      labels:
        app: service-template
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: service-template
          image: ghcr.io/teamslot-app/service-template
          ports:
            - containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          # À activer avec les vraies images (jour 7) :
          # readinessProbe:
          #   httpGet:
          #     path: /actuator/health/readiness
          #     port: 8080
          # livenessProbe:
          #   httpGet:
          #     path: /actuator/health/liveness
          #     port: 8080
      volumes:
        - name: tmp
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: service-template
spec:
  selector:
    app: service-template
  ports:
    - port: 80
      targetPort: 8080
