apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: service-template
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: service-template
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
