apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
- ../../base
- sealed-secrets/postgres-admin.yaml
- sealed-secrets/service-template-db.yaml
- sealed-secrets/identity-db.yaml
- sealed-secrets/identity-jwt.yaml
- sealed-secrets/venue-db.yaml
- sealed-secrets/match-db.yaml
- sealed-secrets/payment-db.yaml
images:
- name: ghcr.io/teamslot-app/gateway
  newName: ghcr.io/teamslot-app/gateway
  newTag: 54e73e66a07cb82ddb00f6393497fa9a1f0f44b5
- name: ghcr.io/teamslot-app/identity-service
  newName: ghcr.io/teamslot-app/identity-service
  newTag: 944595e9d5985cdebeebf6fe980046a445eb6a71
- name: ghcr.io/teamslot-app/match-service
  newName: ghcr.io/teamslot-app/match-service
  newTag: 7a821a2aaaa7778de505719e0fb86e2f0e1c03dc
- name: ghcr.io/teamslot-app/payment-service
  newName: ghcr.io/teamslot-app/payment-service
  newTag: 73f02ea9ce654dbafae3edfd208e3eb40dd727c5
- name: ghcr.io/teamslot-app/service-template
  newName: ghcr.io/teamslot-app/service-template
  newTag: a15cc0603ddace3ebc6c90bb1683155e4ce907f7
- name: ghcr.io/teamslot-app/venue-service
  newName: ghcr.io/teamslot-app/venue-service
  newTag: feafe8ddadb431cdd0fa05f37e9bc5282266df07
