apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
- ../../base
images:
- name: ghcr.io/teamslot-app/gateway
  newName: ghcr.io/teamslot-app/gateway
  newTag: 54e73e66a07cb82ddb00f6393497fa9a1f0f44b5
- name: ghcr.io/teamslot-app/match-service
  newName: ghcr.io/teamslot-app/match-service
  newTag: 73f02ea9ce654dbafae3edfd208e3eb40dd727c5
- name: ghcr.io/teamslot-app/payment-service
  newName: ghcr.io/teamslot-app/payment-service
  newTag: 73f02ea9ce654dbafae3edfd208e3eb40dd727c5
- name: ghcr.io/teamslot-app/service-template
  newName: ghcr.io/teamslot-app/service-template
  newTag: 1ee16f42bd0e19f4cd03cfd4136f3a63a1a21914
