---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: identity-db
  namespace: staging
spec:
  encryptedData:
    DB_PASSWORD: AgAFuJUTUyzgLBhJnJcSr2e3Ot6XVPcSfCptIpPN/X3bZqYMMwcqE7BlWQznPIpRxixM9ZyCPgNj6v8nBylVoSDgZ1EtryF2h94fCczdGif4HyHhH9c+59Pkd7REGWNCOJffg2Sz9k3I0z1VRyUUeDcNxfGm0mT1YyKK6Ovoo3SNU1cRU3BhqrLS5f0/d9zm8KtwmL8b8CXglkS4bBNbE5jcPJY5LGkCteOr1RrLZuQDj8GG1+AretjcgDT/iYZGIYZ5StPG1AGkedzqEiO2Aw2vJPkVyhZWB0uvk2aG+XfjTFTjnZye2NuwnCyMDD+qF/RBQ5tKn7nwg2Y2QDthZtUIjM0IjP5bCDiBrL5m2T8Cl20bWMKO/s4hDsRR40vSdQd+sDcGXeSnQ0oKE06g0StVrsC9rABR3Q9bwll4eLWdK92br9x0USAPhI3mSM7Iaso+VDS55LqH1aybzXtyD9j14aBbslrYxui/2mgraT17l8vFxkRY4yaUdLmmfsoLfstHe+w/8Mph+z7KgouEePL9EPelnFcJBp2qZxTYEj73CqYzYfZ/hziLz5w90+dMLWdD0LJUwPVc7+6e8c55sUBPrqgXzNRFWiEOQA9ftbUtSxfzyXvgsWtX1xQXyh1kt5O/fOQ5+hp6peQIGhCIodbNSM5ixiVpy9mWaDleV0owcaaKZzHpjQRl2HdtCn1GxsL10zutWXa/em6VIHA9bGWNOfZPg989DP6ClqR3GKipwA==
    DB_USER: AgBhWgXlCzZiMLnB4AbgN2QN8xHXaVpIcb8LGKhvz7xOkKRoquw7gnjCSKIJukGRe7ypcMnW5VLBTqtacepBxR1Zx9NZ97KG5pHzcyQoz/jC1JUvbyx6MIm7Eb/WUbNo7lRe8lpPBi4R7k804ZI+ePKtO+FkvSL2U63UWeePbiHYB6tkFS9GlajfIci3p6PNg1hFY+gWmXC0xYpVvCCgBqfvTHqSaND++qCQpfthg2LeUM2+SSEu4Hw8HU7V+mq0j86q/Y126GU61XTMVwMmchbznwHg+FlEusAB9D5U9nu9l7O3zSp+EvxSw0c4ChdeIWE1KZXUR4Bei3VictTYXEwTWAOYSMEEJUjo1s1U+BlWyoUW5r9gom+6VBmTQHxaQ/xkJ1dKGeCS17qGQUTmU9QDz9VJj4thH9HwZM2nW0SPVAdSenWj53CupZzneJ75wEDt3zGAdZWnvq9HffmSA6DyusLjStguc6TNpTlYyzbNy71fh/fNCNDdHNeJsh/kLHgmwE3y2Ut0AcjXVdIx/LfxSXdTIuLXb8B8JqGugp20DA/JedU6nc0+GkBOngpYDF/yPrzo3/hXIK9zyYpTGfzXpg75Wwbmud1u+IaD8tr3iVtet5y9NczWDnuu3nOoqMJwyeTTaxrV0RexS0QdcdOIDEuwadpuoU6E7+N4qlxmnU5jDzlLiF0lOOx5rxXdiZyxX0qtPVkChFsXLXm5
  template:
    metadata:
      name: identity-db
      namespace: staging
