---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: match-db
  namespace: staging
spec:
  encryptedData:
    DB_PASSWORD: AgAAytfw3eaj4EbtRU3+RxpCASSw5bDpiTyv++TASXhUXqol0/0P8IwV8+2GnAABh5KqmxiGePXoDFUTS48QVq5uANEZOE+/21Kt//X4J1dpPg5ItOY9kLUt7tiFaaPm/wc2aNPMNYcUt3I/77s3VvppoZas9NlpEW1Zuof7pCC8gDAKf0nmNHeTfowYeYFgLCYsMNetB3r7z3ONHz1o2BaS5IqCyy2UdDWDjEGRs2T9+l8ABqybIoGHGdjcbRH9aAgirPRDcBdR0NMaIsZ3tXTi94tdVR3E0UpREAIHrJSf7UqSHsphYvYIkjk0QzRF39ck+BsVE//I+YgGfQMY35p77vNjTTPOcNVllwDHTlnDmVU0KwuSVUmQhtLCILyqid8XbGPt80EJFkoAPsDdqDoJ8SD5zyBP+QzFYgBMugwkFKBQE2TdPF5Nl7KHuuOTpc083ZN3DfpkBl6qiLIDM/44SCcxgw3lmTs+ezhLeQzjpXSvCl95NqCK1wGJydogJB9cH6evylg27WYNsZUILpqTYESPiSkJX1ibRqHp3ven7J3ciZUmZSFhLh4p8xc7rwRHatmmRtUiQxMaS7Pt5Q/muUxjF8GCTm+wWZ1ND9MMrtm7Wzcbz5mmA8+EzLMbYyd2GolsGSfCN77DsvyhQKnm/WL8M0q9S/+GSTnUd2063HaRmM0gtwKW6c8Wysf22gFPMPQ+m8JfkXhtOXgy3nMvWiHmpvMkfYAEiHirVTJycg==
    DB_USER: AgBLhkBM1LjFrvXAyieAmGcw0Uj6d8KjMRuqJ962RPZpGb3HKvPqxt+9BV/mnupbc/wyyCIzTC9EV4XLMJtF6KZ7ljyaQzWFc8hPvA3uhU3soXB7AXLcjmkNYm2P7poylQhah1+aV4walt0DVCYQLjHt0M9N0WtBo7QOWL9lIA1CRvIzryI5pR/2uHIy3td+CDsjZicAK7D4jhdqyHF3VpyoLG7dXZSpHlLAQ3uVKkYQdE0poMvw0XAvbmase51TOxlAzn4PdDB/KZW0kuo7c3qwnq62my7O5eGau1Og0uEN57eNjhxGDtbjnNOVJbAfdQonlAjPoOsTBVMUN7HUEw9xfzmEcxbuvKZooyys3eMnx24N4byzU2Nw6PiKA2w0uqItxoi1E0ODt5OwvLxAxfeD4obfxZAyRrLyTC1sTnm1IrinhcesBa+SC/CMXxOEAjKv914GStMQZ78FA3mb2t8yZ+ckd038odEYiOdR1jieJODLx1R9OILxhzWEf1Z5WYEnC98pOnvFKpZLfhwDT96zagc7tPUT0+XvEwtgzr1TfeHZEGWQqG9zpdGLrO+yfeP4JetyKdR32DqrAqhV4pedpDIpdTPVqF10dqbVSIHrukHE7sZSl6cX603y1PakKOWykDkFVWiuKWbB7tPlzDnGjJKjF2NV5r5kDSxo1I3v3lEHer9WF8tPsWbE+VSDB7GyLETXfkaGGcHe
  template:
    metadata:
      name: match-db
      namespace: staging
