---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: payment-db
  namespace: staging
spec:
  encryptedData:
    DB_PASSWORD: AgBIPi4Hi9fq4llGLilPY5bFioMfujPS67K2PFYkEnEPPkx5qUdphod3Oa0RCfFxMQZXR7g/+8fO1eNlNR0V4Dj2ncxErnIcWC3668sbhdHbtm0qpQ1B/p0ULpWnkcCW/oi76paeBYH7Nz4Bz84Vri3UYeLhzKp9D+hwVf7doiyg3zsH5m+kNq186OUgHHlvvCNjEjVRKofbTXlYjG7UOAXubRp5HIIuLME+BO7RyTWYz0rjZHZGr4+TRX5yjYSTsnJ7cRMTJgMdn51uBI+fci3CNgLVzR5VarFo0NuZVSoray9uqft86ayaV0UDaLeuSSKQWEsT635ttCRzXQNSj2kQhsp4ROy7xcJlYPau+cUxwKZNftW+932btlL7HuA3ZpR82XDGsFb9dL65KDNYW5sN3bJRfjaQW4FgiknuYTgsmOKIHTqYtmdTHi7JgYj/J8shIZTcybLPilaEpqmXIuZoC56We28PMDqecV9NZQL3vg3ax4d2TOTexABUAJjL8KKuSYK5K/hvN+9SvZLYWWheH86qepFXcv4V+AFAGTI1Ze3nhYagr9myqLGRwrqJGMoZnY1V3JyFpYJf3dafbSKaGSagU3biskuieYfoO0wResHmB7G+LnCrFeANK5WvOYy6ZOBj2QsbSjPief4ln2cyFfnw5XffvLPAT+ZsSlbq6Xx/2r0qyzNRUv4kGs0w5m8SCyIOm/h8f1yFYxbWZNBkX67xiYUB/BvEBMfmRFViCA==
    DB_USER: AgATc037xAR91DZZ0v3EmpM8P71lRQUAmDj2DNN57JAnd/e4AxwTI94H1/WM9ubdsZ03skCArs2pU85SxDtDpMqDb5vL83bpwD1Z0e0DeCY/3QlMaFHj6HdMk9zw0N9EYxt3xOrvfplRIyJdg4wIzo/QjfCQ8FIZ6p18dOtLJPmrzkLVzaYBbOfFx1zp8q6n0hl3X8MrOehu2fsMTNi0Gkv7UHJGjkSkZMZQ+8FrsFke6mH77TqVZyT70+xwYCqKBKxc5c+ku/GgunKZY06iIn3Zy2hUrtPUoOP0jDispe5CYRPQgxkVchPIBLfGodX/8XBmuB52v5RP5ymRVyPR6emD+PjuBfm09P5u4LXzeQbiD7ApkZ7ic7hP0oc4hyW7UnPkph7OXkO6S7+n8g2iQ4vUHtAMU7k2IoTkw7QkPhjSK8QosUX4YViatX70aywSsa/ziNdPXvKCumTnxUO8JcSRuSXIONlSHql6nIcS3Khs9BzFRqBNp5WTwvk243TZFb30CHCxhAV9Y0xxCkxs7VHeNRqsmCAFjuwuviXoced670u7Ja1oC9c4SwCO5pMAhQalegsMIFLlwmWyyk8MjA5d8KoFx1NVwYROvRIj40S+9xxyAPbqJ708i3oR6WoGOffD3fUTFq/d1sJS3Uml/R0IW2FiZchdl50gpNsOdnyT8JXR/NxaqDNQX6Dbck477ohHMURL/jXanjV5YM0=
  template:
    metadata:
      name: payment-db
      namespace: staging
