---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: service-template-db
  namespace: staging
spec:
  encryptedData:
    DB_PASSWORD: AgAhBlb3y61X4dMG+4V0w+82iYPQsFYdWWXTveptnIqzlnJzJ8tKQd5oDgze83861m6Uw6lOEh2nTN+0YUTgh+D4gDE+YtGwphwiT3QefGoPVDtvXdma14q0BDzxhZVzpTd85PMJyw/nW3HM9nOb1CFLB6b1bYUk8TlLVUtVtx9Fqy1aLTRxRX0ElHh2YDN5kJM5NwMESNefHJwXaSQfOM2y6KyQzBWJYWuDXKmqRwn489fcdUqLSknuT0OxgUIon5c2hVENfTWYH9G9vkVCa3j1JE+4msw72NkPU3yOAuQQ5ql7zqYxvCtj+05PIq6liBLGbgjE+SU3cqKXmdQX3Li8ZA9eB+Crcy3HwILCpnUTjed89+V9l5kxzkss0Yi/0fKpFG7cLI26hEgsW1dmP5hpsJqZa8kLbIOLyWIZPa9RNnzgf+WbXfTbnfqspc0t9Ii4lj9O/5NdmQ8hhBmtxneMEKXw+Wh4VwUn3gbaOhUNX9QYZ1+8yXamXa3Nt7jiBk051TU6WVFidw+jNlr844/Juczo3OiVqeupBmXTW2p3jB+o/pyVJ0zzxAHQR0EB7fLS6Q5oE1VJzY7xAM4Dx0ZSCnBjFqZ7PYwDXdFyrsPdqSLzKUudJx3k5ta9hiPMYcgS0gOljYGz8zKekZFvFfkf4hDcE2QOj8cnT2XBSmgL4/kX4luQjp5z1vgnqjiXbhKD4U8haD76dp0TE5vfsbHlwoqZFqctpA5jwzSRNOEt+A==
    DB_USER: AgAz7BMkAI43spx14yEz0Ai3m/WQGAHb5+rOe0y1MwAtbAKNxh5UYZsEmZ8Ih7u9FhmmzyAWqyr+vW1LJStGI5iVqpKr1V4Tvdx9l4J89Hf79ScDOboHcxkfAFe6qMcok9DNTahnH9kmQQ7sMEi5XWKYF7N5F1SyP+finwvjHrxYIOT5eGpB1qPA51IbnusDBcHGBJX+YbOgWoccQ6kNQtiWilf+stQmZE13+FH5/NsWiB5dsIDuArvyiBN0SG55sYbbzcA54C2ZzzVEfwrUcU2KJZwo3nZrU8HmyxgbtDf6Md0Q+iyPfTVJ2lkh7PixbcNpDuDiA/4/hpAegBD1/7pNF0PhEvEOgso9W5aizmI9KEiRovzKZICHZu4QCZLAsO1DnG2Q9e7mpHMc2xkCkVlQHp6RkfoH5mjDGs409bsPnLeF8ZeXZQ7t65nI1gzE2XftJdBWuP7svWm4Yt+Y4Z34QSqvmV7itgj1bkMttqFS2eNsO0fzc3sdtnstKf4+/6NVmzYYqRV8pq/HZh9/n42EmqSjyScBcLt8DCCFNf+LgmDgG+WJh084GAHQlScllucTfUK9ixLOjgRPLyrmEayO0wOrsqTp7YNWZO/AUF2LEfazQtDXGI7TRbOnpc6Agma5ba9Ay0rU+LOoBl48WFHqaVmnhbRdtF9Z5zQrjPan08Jlj/7Sqc7lYjX/XtsSWgnM8ORgcnbiqQ==
  template:
    metadata:
      name: service-template-db
      namespace: staging
