---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: venue-db
  namespace: staging
spec:
  encryptedData:
    DB_PASSWORD: AgBtSLlEv99PqomVa3LnXMsNrXg43j7INzCkX5sg19xbsIqkcCl7sw4BK6MD6UPq2DJaOc30dd7NZcp932qXjQXWwn12jF3OYAHRj/wCTaBLvVtNTosJ+eF0iCZwZ7M70dPX42jZkbAplW0kHfGOxqFJ6ezhJlxd0gOUg6BxxYmSyPm3lMiXJC6IyCg3a+tl0ExH9LpHlqepXdf+4jrnmMC+b/IlD0GoNEcYewPpIJi8t2NA/ysi74QiEOh/HHmp9RhIjkO/FMBAKZ6dFIZK/lrpBcWyAPMi9Y1OKO5MON0b6QJnXdFiAr5NCMWQ54G/TvuTWedsUJKd4lwqtirvfXClh1EAbC4eWTMZhY8xJjsqTBYBB/iE654dnMSxjYcsNUXsZX0KZBClT2FFHIrjaUGWILjJ5aZg29tnfkkAwojc40g6PgOhUcHdcthWy9NJfQAHGdJoGwz737YsdkhRl3THp+Hvg/E41pLmc9yj7vaKZiVVO8bMcnw+cMVrQquIq52hFgtQlIAVhu485uRN86a0UNKGbP9BNsXbYC7RIlhKFhCEEsKN1cQOS+NidtsuqCnSfHRXxPndc6gAYA0SiqiPCGyTJg7ZVwGfEePB8oKL/p3MHR/sG6ocTS6Sj5EZLORuMH8GtZ0h9dbdIUXfJuOiv/zBLkL0zky2+tHESKXRLQhq/NPqAdBOjRKATEcIDxNxzLSNm+VDEpV3+h96ivCZWE/+sojKbUnGDRttqtbIbA==
    DB_USER: AgAc2S+WNTs3Y39l3Vu84SqVFlEWzWn8sjwD3lVgAjgwIoK4zHNhpiY1ufQBNc0siY6TmIDxmJ/Luky59dYbH+VYefzfbrqyg8vFYQy8Mru7qzb5QQdNZg7Iyt7NBMtzyAe5j9B4FTpqb1RBAZLKpK5zoXAHIuqxyiwwCKc6T56TG/nkOrNEgnLn+lRcwavsgvebGpOUAhcqu/zV6GcSgtRpO3KgH9X/hRdf96mgND14L96Z7IB4Jgn7pFUaEuCECBPnllBz9NSj/CtdChsfXMcoDt5YnQH3ZFQzpgdUu4ywjwhcz9rRMEdSeVt3tzet39NyRlkDQcgS1QKO4JpseGjy4+LWTsPsFlsq2yJrReWXQsBXHWU/V4JUrP3fkjuFLhOK2mEgcbRos/ZsyS4n78H5yWSH5WCPLClrUVzPvMgCT6Jhg7HxpEW3wKhBNjaY8QbbQPrb9jSTc9uEvb7NOaHCC9uVhh4oLd+SEuil1pKl8pmO6jSnpE3LredfHhN2D0FFuhhdTH5Z0M2dmDVSb5/gypdJPUcEIoOnrDL1nUqhQeXr8R1Q3a8wBVPzx7pl5aRG9FdYvB2kvi/kyX7ZIjqqGijyUdovvBIeiZVDfExVU6nOwoLdQigtYr56pZ4Z0+yu4VINPp9OvdhyMLSAslcQpCbPfjR1BiFva6n0D/VJ/zf/yHVFcCrBpQFQhb/nP2rtN+Gn89BjiRiL
  template:
    metadata:
      name: venue-db
      namespace: staging
