name: gateway
on:
  pull_request:
    paths:
      - 'gateway/**'
      - '.github/workflows/java-service.yml'
      - '.github/workflows/gateway.yml'
  push:
    branches: [main]
    paths:
      - 'gateway/**'
  workflow_dispatch:
permissions:
  contents: read
  packages: write
jobs:
  ci:
    uses: ./.github/workflows/java-service.yml
    with:
      service: gateway
      name: gateway
    secrets: inherit
