name: service-template
on:
  pull_request:
    paths:
      - 'services/service-template/**'
      - '.github/workflows/java-service.yml'
      - '.github/workflows/service-template.yml'
  push:
    branches: [main]
    paths:
      - 'services/service-template/**'
permissions:
  contents: read
jobs:
  ci:
    uses: ./.github/workflows/java-service.yml
    with:
      service: services/service-template
      name: service-template
      sonar_project_key: teamslot-app_teamslot
    secrets: inherit
